Выполнил первое задание
htmlacademy-htmlcss/1964883-sedona-33 pull request #2
Opened 2022-01-23 22:16 UTC by PavelMo143

2022-01-23 23:19 UTC, PavelMo143 commented
Сделал шапку сайта

2022-01-25 21:59 UTC, PavelMo143 commented
Выполнил задание разметка главной страницы

2022-01-26 17:56 UTC, SidSpears69 requested changes

2022-01-26 17:56 UTC, SidSpears69 commented on index.html
> +            <h2 class="advantages-title">Там есть мост дьявола</h2>
h3 тут должен быть

2022-01-26 17:56 UTC, SidSpears69 commented on index.html
> +              <h2 class="advantages-title">Настоящий городок</h2>
Тут h3

2022-01-26 17:56 UTC, SidSpears69 commented on index.html
> +            <h2 class="advantages-title">Небольшая площадь</h2>
И здесь и далее

2022-01-26 19:39 UTC, PavelMo143 reviewed
поменял h2 на h3

2022-01-26 20:50 UTC, PavelMo143 commented
Сделал второе задание

2022-01-26 22:01 UTC, SidSpears69 approved these changes

2022-01-26 22:03 UTC, merged